name: Github Unfollow Tracker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # every hour at minute 0

jobs:
  scrape_hourly:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.7"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Run script
        run: |
          python main.py
        env:
          APP_USERNAME: ${{ secrets.APP_USERNAME }}
          APP_TOKEN: ${{ secrets.APP_TOKEN }}